[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[feeluown-core]
source = "pypi"
pypi = "feeluown"

[feeluown-kuwo]
source = "pypi"
pypi = "fuo_kuwo"

[feeluown-local]
source = "pypi"
pypi = "fuo_local"

[feeluown-netease]
source = "pypi"
pypi = "fuo_netease"

[feeluown-qqmusic]
source = "pypi"
pypi = "fuo_qqmusic"

[qasync]
source = "pypi"
pypi = "qasync"

[qliveplayer]
source = "github"
github = "IsoaSFlus/QLivePlayer"
use_latest_release = true

[src-8]
source = "github"
github = "outloudvi/mw2fcitx"
use_latest_release = true

[src-9]
source = "manual"
manual = "0.2.2"
