# This file was generated by Update.hs, please do not modify it manually.
{ fetchFromGitHub, fetchurl }: {
  feeluown-core = {
    pname = "feeluown-core";
    version = "3.6.1";
    src = fetchurl {
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).feeluown-core;
      url = "mirror://pypi/f/feeluown/feeluown-3.6.1.tar.gz";
    };
  };
  feeluown-kuwo = {
    pname = "feeluown-kuwo";
    version = "0.1.2";
    src = fetchurl {
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).feeluown-kuwo;
      url = "mirror://pypi/f/fuo_kuwo/fuo_kuwo-0.1.2.tar.gz";
    };
  };
  feeluown-local = {
    pname = "feeluown-local";
    version = "0.2.1";
    src = fetchurl {
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).feeluown-local;
      url = "mirror://pypi/f/fuo_local/fuo_local-0.2.1.tar.gz";
    };
  };
  feeluown-netease = {
    pname = "feeluown-netease";
    version = "0.5";
    src = fetchurl {
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).feeluown-netease;
      url = "mirror://pypi/f/fuo_netease/fuo_netease-0.5.tar.gz";
    };
  };
  feeluown-qqmusic = {
    pname = "feeluown-qqmusic";
    version = "0.3.1";
    src = fetchurl {
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).feeluown-qqmusic;
      url = "mirror://pypi/f/fuo_qqmusic/fuo_qqmusic-0.3.1.tar.gz";
    };
  };
  pypinyin = {
    pname = "pypinyin";
    version = "0.40.0";
    src = fetchurl {
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).pypinyin;
      url = "mirror://pypi/p/pypinyin/pypinyin-0.40.0.tar.gz";
    };
  };
  qasync = {
    pname = "qasync";
    version = "0.13.0";
    src = fetchurl {
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).qasync;
      url = "mirror://pypi/q/qasync/qasync-0.13.0.tar.gz";
    };
  };
  qliveplayer = {
    pname = "qliveplayer";
    version = "3.21.1";
    src = fetchFromGitHub {
      owner = "IsoaSFlus";
      repo = "QLivePlayer";
      rev = "3.21.1";
      fetchSubmodules = true;
      sha256 = with builtins; (fromJSON (readFile ./sha256sums.json)).qliveplayer;
    };
  };
}