# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "0.0.0.20200413";
    src = fetchurl {
      sha256 = "0xaclj29b7xgqin8izkabrm2znp1m01894fngyxrhwbf9nbncp4g";
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/latest/AppleColorEmoji.ttf";
    };
    
  };
  fastocr = {
    pname = "fastocr";
    version = "0.2.0";
    src = fetchurl {
      sha256 = "1s0cgfknjrws8c1mfj656gd9cjbwh3cspf14p2qvs10hlf7jvbh2";
      url = "https://pypi.io/packages/source/f/fastocr/fastocr-0.2.0.tar.gz";
    };
    
  };
  fcitx5-material-color = {
    pname = "fcitx5-material-color";
    version = "0.2.1";
    src = fetchgit {
      url = "https://github.com/hosxy/fcitx5-material-color";
      rev = "0.2.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0drdypjf1njl7flkb5d581vchwlp4gaqyws3cp0v874wkwh4gllb";
    };
    
  };
  fcitx5-pinyin-moegirl = {
    pname = "fcitx5-pinyin-moegirl";
    version = "20210614";
    src = fetchurl {
      sha256 = "07zk96havkli1i8945vgbk1nvym3jxyy34gglxhgx1639z1pmh52";
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20210614/moegirl.dict";
    };
    
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "0.2.3.20210625";
    src = fetchurl {
      sha256 = "1yl6nfi7jk3q5dl9digx77d37j7f6ggqsrbz07bcw0h8xyk0w21j";
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.3/zhwiki-20210625.dict";
    };
    
  };
  feeluown-core = {
    pname = "feeluown-core";
    version = "3.7.9";
    src = fetchurl {
      sha256 = "1j87x3gig0am4b9igkwka4rymhkg154wdv83c8p99b1l7bk0wrh9";
      url = "https://pypi.io/packages/source/f/feeluown/feeluown-3.7.9.tar.gz";
    };
    
  };
  feeluown-kuwo = {
    pname = "feeluown-kuwo";
    version = "0.1.4";
    src = fetchurl {
      sha256 = "1knflrhipadmqqsgs9cysp1hn9lx58q2x00bd1lrbm16nq1ngcyr";
      url = "https://pypi.io/packages/source/f/fuo_kuwo/fuo_kuwo-0.1.4.tar.gz";
    };
    
  };
  feeluown-local = {
    pname = "feeluown-local";
    version = "0.2.1";
    src = fetchurl {
      sha256 = "0ifl2d5qwx0cyh6i1c952ldwwzdcwzbj98fxx2b8dky3wlla96d7";
      url = "https://pypi.io/packages/source/f/fuo_local/fuo_local-0.2.1.tar.gz";
    };
    
  };
  feeluown-netease = {
    pname = "feeluown-netease";
    version = "0.7.1";
    src = fetchurl {
      sha256 = "0yzhbpwlsg3n8q21xfd8hfnf7fc9pcv69kqdypij3xpdrfadvcpg";
      url = "https://pypi.io/packages/source/f/fuo_netease/fuo_netease-0.7.1.tar.gz";
    };
    
  };
  feeluown-qqmusic = {
    pname = "feeluown-qqmusic";
    version = "0.3.3";
    src = fetchurl {
      sha256 = "0gwcg8xc0nxk5dl6f2kl2mzi0fr70qdrv29fk151pikg3hmh5i3l";
      url = "https://pypi.io/packages/source/f/fuo_qqmusic/fuo_qqmusic-0.3.3.tar.gz";
    };
    
  };
  pypinyin = {
    pname = "pypinyin";
    version = "0.42.0";
    src = fetchurl {
      sha256 = "18fkl6hagg6w8pz48r6af9pqvnz6fdq7zrf783a3h8xx0frh7w62";
      url = "https://pypi.io/packages/source/p/pypinyin/pypinyin-0.42.0.tar.gz";
    };
    
  };
  qasync = {
    pname = "qasync";
    version = "0.16.0";
    src = fetchurl {
      sha256 = "1c9058j2l4jg46zicm7n3pc9jdnd617lwg60kv6lmqrlfyv1zfv5";
      url = "https://pypi.io/packages/source/q/qasync/qasync-0.16.0.tar.gz";
    };
    
  };
  qliveplayer = {
    pname = "qliveplayer";
    version = "3.22.3";
    src = fetchgit {
      url = "https://github.com/IsoaSFlus/QLivePlayer";
      rev = "3.22.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1qajarsxmmd39ryk3218av12y0zkasap8j7lpnic1frhb26p7m9r";
    };
    
  };
}
